# 服务端口
server:
  port: 8222

spring:
  application:
    # 服务名
    name: service-gateway

  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          # 使用服务发现路由
          enabled: true

      routes:
      # 设置路由id
      - id: service-acl
        # 设置路由的uri
        uri: lb://service-acl
        # 设置路由断言,代理serviceId为auth-service的/auth/路径
        predicates:
          - Path=/*/acl/** # 路径匹配

      - id: service-edu
        uri: lb://service-edu
        predicates:
          - Path=/eduservice/** # 路径匹配

      - id: service-ucenter
        uri: lb://service-ucenter
        predicates:
          - Path=/educenter/** # 路径匹配

      - id: service-cms
        uri: lb://service-cms
        predicates:
          - Path=/educms/** # 路径匹配

      - id: service-msm
        uri: lb://service-msm
        predicates:
          - Path=/edumsm/** # 路径匹配

      - id: service-order
        uri: lb://service-order
        predicates:
          - Path=/eduorder/** # 路径匹配

      - id: service-oss
        uri: lb://service-oss
        predicates:
          - Path=/eduoss/** # 路径匹配

      - id: service-statistics
        uri: lb://service-statistics
        predicates:
          - Path=/statistics/** # 路径匹配

      - id: service-vod
        uri: lb://service-vod
        predicates:
          - Path=/eduvod/** # 路径匹配