server:
  port: 8003
spring:
  application:
    name: service-vod

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  vod:
    file:
      keyid: <your key id>
      keysecret: <your key secret>

