server:
  port: 8002
spring:
  application:
    name: service-oss

  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 单个文件上传最大值
#  servlet:
#    multipart:
#      max-file-size: 3MB

aliyun:
  oss:
    file:
      endpoint: <your endpoint>
      keyid: <your keyid>
      keysecret: <your keysecret>
      bucketname: <your bucketname>