# 服务端口
server:
  port: 8004

# 服务名
spring:
  application:
    name: service-cms

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.223.110
    port: 6379
    database: 0
    timeout: 18000000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lemon_edu?serverTimezone=GMT%2B8
    username: root
    password: 12138

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/fatehole/educms/mapper/xml/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

